# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='abbreviation',
            field=models.CharField(default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='short_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
