# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20180326_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.Conference'),
        ),
    ]
