# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180326_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='alternate_uniform',
            field=models.ImageField(blank=True, null=True, upload_to='images/teams/uniforms'),
        ),
    ]
