# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_alternate_uniform'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/league')),
            ],
        ),
    ]
