# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users'),
        ),
    ]
