# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_subscription_ends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_profile',
            field=models.BooleanField(default=False),
        ),
    ]
