# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_private_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='private_profile',
            new_name='is_private',
        ),
    ]
