# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_period',
            field=models.CharField(blank=True, choices=[(1, 'One Month'), (3, 'Three Months'), (6, 'Six Months'), (12, 'Twelve Months')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_renews',
            field=models.NullBooleanField(default=None),
        ),
    ]
