# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180407_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_period',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
