# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180415_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
