# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20180405_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='order',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.Item'),
        ),
    ]
