# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20180405_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Dispatched', 'Dispatched')], default='Pending', max_length=20),
        ),
    ]
