# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_cart_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
