# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20180412_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='postage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
