# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180326_1050'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='teams',
        ),
        migrations.AddField(
            model_name='item',
            name='teams',
            field=models.ManyToManyField(related_name='item', to='teams.Team'),
        ),
    ]
