# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 20:43
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180326_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
