# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20180410_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_image',
            field=models.ImageField(default='images/news/categories/default.jpg', upload_to='images/news/categories'),
            preserve_default=False,
        ),
    ]
