# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
