# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_item_image_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='published_date',
        ),
    ]
