# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180326_1050'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='teams.Team'),
        ),
    ]
