# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180401_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_post',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 12, 30, 29, 355000)),
        ),
    ]
