# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20180402_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='last_post',
        ),
    ]
