# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 20:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_thread_last_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_post',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 21, 35, 4, 173000)),
        ),
    ]
