# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_thread_last_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='last_post',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
