# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20180404_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
