# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_thread_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.Board'),
            preserve_default=False,
        ),
    ]
