# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180323_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
