# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', tinymce.models.HTMLField(blank=True)),
            ],
        ),
    ]
