# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_auto_20180326_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('game_time', models.TimeField()),
                ('game_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Postponed', 'Postponed'), ('Suspended', 'Suspended'), ('Completed', 'Completed')], default='Scheduled', max_length=10)),
                ('innings', models.IntegerField(default=9)),
                ('home_team_runs', models.IntegerField()),
                ('home_team_hits', models.IntegerField()),
                ('away_team_hits', models.IntegerField()),
                ('home_team_errors', models.IntegerField()),
                ('away_team_errors', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_away', to='teams.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_home', to='teams.Team')),
            ],
        ),
    ]
