# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Pre-Season', 'Pre-Season'), ('Regular Season', 'Regular Season'), ('Postseason', 'Postseason')], default='Regular Season', max_length=15),
        ),
    ]
