# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team_runs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
