# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20180326_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Postponed', 'Postponed'), ('In Progress', 'In Progress'), ('Suspended', 'Suspended'), ('Completed', 'Completed')], default='Scheduled', max_length=15),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='teams.Team'),
        ),
    ]
