# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180326_1050'),
        ('games', '0005_auto_20180328_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion', to='teams.Team')),
                ('finalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalist', to='teams.Team')),
            ],
        ),
    ]
