# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='runs_per_game',
            field=models.FloatField(default=0),
        ),
    ]
