# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20180331_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='champion', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='season',
            name='finalist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalist', to='teams.Team'),
        ),
    ]
