# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20180331_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='games',
            new_name='games_played',
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(default=2018, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.Season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)]),
        ),
    ]
