# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20180401_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='season',
            name='runs_per_game',
        ),
    ]
