# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20180401_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='schedule_length',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='season',
            name='series_score',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
