# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20180409_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_premium',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
