# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_game_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_premium',
            field=models.NullBooleanField(),
        ),
    ]
