# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20180422_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
